---
- name: gathers facts from AMI
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/vars/david.dev
  tasks:
    - name: Get the info from an AMI
      ec2_ami_find:
        name: "CentOS Linux 7*"
        owner: 679593333241
        #ami_id: "ami-9bf712f4"
        region: eu-central-1
        sort: creationDate
        sort_order: descending
        sort_end: 1
      register: ami_find

    - debug: var=ami_find