---
- name: Template for docker repo.
  template:
    src: docker.repo.j2
    dest: "{{ docker_repo_file }}"

- name: Install the docker packages.
  yum: name="{{ item }}" state=installed
  with_items:
    - "{{ docker_packages }}"

- name: Start start docker service.
  service: name="{{ item.name }}" enabled=yes state=started
  with_items:
    - { name: "docker" }

- user:
    name: ec2-user
    shell: /bin/bash
    groups: ec2-user,wheel,docker
    append: yes

- name: Pull Redis image
  docker_image:
    name: redis

- name: Pull algo image
  docker_image:
    name: davesade/algo

- name: Start redis container
  docker_container:
    name: redis
    image: redis
    ports:
      - "6379:6379"

- name: Start algo container, linking with Redis
  docker_container:
    name: algo
    image: davesade/algo
    links:
      - "redis:redis"